version: '3.9'
services:
  postgres:
    container_name: postgres-db
    image: postgres:13
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
